server:
  id: dev
  file_path_template: tmp/files/:date/:id:ext

session:
  access_token_exp: 900 # 15 min
  refresh_token_exp: 12969000 # 15 day
  access_token_refresh_threshold: 300 #  5 min

github:
  client_id: 67d44b6101f98c012bd7
  oauth_redirect_uri: http://localhost:3000/login
  oauth_state_exp: 600 # 10min
